name: Conditions 
on: push
jobs:
  skip-or-run:
    env:
      RUN_ID: ${{ github.run_id }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "${RUN_ID}"
      - run: echo "Hello"
        if: ${{ contains(github.run_id, '1') }}